# Generated by Django 4.2.7 on 2023-11-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topsis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kondisi_ekonomi', models.FloatField()),
                ('kondisi_rumah', models.FloatField()),
                ('pekerjaan_orangtua', models.FloatField()),
                ('penghasilan_orangtua', models.FloatField()),
                ('status_orangtua', models.FloatField()),
                ('tanggungan_orangtua', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
