# Generated by Django 4.2.7 on 2023-11-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topsis', '0002_beasiswa_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, verbose_name='Nama')),
                ('kondisi_ekonomi', models.IntegerField(choices=[(1, 'Stabil'), (2, 'Kurang Baik')], verbose_name='Kondisi Ekonomi')),
                ('kondisi_rumah', models.IntegerField(choices=[(1, 'Batu Bata Lantai Keramik'), (2, 'Batu Bata Lantai Semen')], verbose_name='Kondisi Rumah')),
                ('pekerjaan', models.IntegerField(choices=[(1, 'Wirausaha - Buruh pabrik'), (2, 'Serabutan'), (3, 'IRT')], verbose_name='Pekerjaan OrangTua')),
                ('penghasilan', models.IntegerField(choices=[(1, '> 1.500.000'), (2, '>= 1.500.000 - <= 1.000.000'), (3, '<= 900.000 - >= 500.000'), (4, 'Tidak Berpenghasilan')], verbose_name='Penghasilan OrangTua')),
                ('tanggungan', models.IntegerField(choices=[(1, 'Satu'), (2, 'Dua'), (3, 'Tiga'), (4, 'Empat')], verbose_name='Tanggungan OrangTua')),
                ('keterangan', models.IntegerField(choices=[(1, 'Penghasilan OrangTua'), (2, 'Yatim')], verbose_name='Keterangan')),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data',
            },
        ),
        migrations.DeleteModel(
            name='Beasiswa',
        ),
    ]
