# Generated by Django 4.2.7 on 2024-02-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topsis', '0003_data_delete_beasiswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='tahun',
            field=models.IntegerField(default=2024, help_text='Tahun data diinput', verbose_name='Tahun'),
        ),
    ]
