# Generated by Django 4.2.7 on 2024-02-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topsis', '0004_data_tahun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='kondisi_ekonomi',
        ),
        migrations.AddField(
            model_name='data',
            name='surat_keterangan_tidak_mampu',
            field=models.IntegerField(choices=[(1, 'Tidak Ada'), (2, 'Ada')], default=1, verbose_name='Kondisi Keterangan Tidak Mampu'),
        ),
    ]
