# Generated by Django 4.2.7 on 2024-02-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topsis', '0005_remove_data_kondisi_ekonomi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='surat_keterangan_tidak_mampu',
            field=models.IntegerField(choices=[(1, 'Tidak Ada'), (2, 'Ada')], default=1, verbose_name='Surat Keterangan Tidak Mampu'),
        ),
    ]
