# Generated by Django 4.2.7 on 2024-02-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topsis', '0006_alter_data_surat_keterangan_tidak_mampu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='pekerjaan',
        ),
        migrations.AddField(
            model_name='data',
            name='keaktifan_ekstrakurikuler',
            field=models.IntegerField(choices=[(1, 'Tidak Aktif'), (2, 'Jarang'), (3, 'Aktif')], default=1, verbose_name='Keaktifan Ekstrakurikuler'),
        ),
    ]
